"""empty message

Revision ID: 271934f2c262
Revises: 8bc21cf4f939
Create Date: 2017-04-20 10:07:26.755701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271934f2c262'
down_revision = '8bc21cf4f939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'banners', ['filename'])
    op.drop_column('banners', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('image_url', sa.VARCHAR(length=2083), nullable=False))
    op.drop_constraint(None, 'banners', type_='unique')
    # ### end Alembic commands ###
